"use client";

import { ArrowRight } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
} from "@/components/ui/carousel";
import { cn } from "@/lib/utils";

// Removed NextJS specific imports: next/image, next/link

interface GalleryHoverCarouselItem {
  id: string;
  title: string;
  summary: string;
  url: string;
  image: string;
}

export function GalleryHoverCarousel({
  heading = "Patient Care Initiatives",
  items = [
    {
      id: "item-1",
      title: "Diabetics",
      summary: "Targeted solutions for effective long-term blood sugar management.",
      url: "#",
      image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80",
    },
    {
      id: "item-2",
      title: "Pain Management (Ortho)",
      summary: "Advanced rapid-acting formulations for orthopedic relief and complex fevers.",
      url: "#",
      image: "https://images.unsplash.com/photo-1551076805-e1869033e561?w=800&q=80",
    },
    {
      id: "item-3",
      title: "Gastro Care",
      summary: "Comprehensive digestive health solutions tailored for total gut wellness.",
      url: "#",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80",
    },
    {
      id: "item-4",
      title: "Neutrceuticals",
      summary: "High-quality supplements and fortified wellness products for robust daily stamina.",
      url: "#",
      image: "https://images.unsplash.com/photo-1550572017-edb79a0aa249?w=800&q=80",
    },
    {
      id: "item-5",
      title: "Allergy Management",
      summary: "Rapid cellular relief from severe seasonal and persistent chronic allergies.",
      url: "#",
      image: "https://images.unsplash.com/photo-1584017906762-2567756e1871?w=800&q=80",
    },
    {
      id: "item-6",
      title: "Gynae",
      summary: "Dedicated, sensitive pharmaceutical care optimized exclusively for women's health.",
      url: "#",
      image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80",
    },
    {
      id: "item-7",
      title: "Pediatric",
      summary: "Completely safe and rigorously tested treatments tailored perfectly for children.",
      url: "#",
      image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800&q=80",
    }
  ],
  className
}: {
  heading?: string;
  demoUrl?: string;
  items?: GalleryHoverCarouselItem[];
  className?: string;
}) {
  // We are hooking into the context generated by ibelick's carousel primitive
  // This carousel implementation doesn't expose `setApi` natively, so we are keeping
  // standard state control internal to the carousel or omitting direct DOM scroll track.
  // Instead of passing `setApi`, the primitive controls its own internal indices via context.
  // Because ibelick/carousel exposes `useCarousel()` internally for Navigation buttons,
  // we will slightly adjust the DOM tree below to use standard primitive wrapping.

  return (
    <section className={cn("py-24 bg-transparent w-full z-10 relative overflow-hidden", className)}>
      <div className="container mx-auto px-6 max-w-[100vw]">
        
        {/* Header Block */}
        <div className="mb-12 flex flex-col items-center text-center md:mb-16 w-full">
          <div className="max-w-3xl">
            <h3 className="text-3xl lg:text-5xl font-bold tracking-tight text-white leading-tight">
              {heading}
            </h3>
            <p className="mt-4 text-lg text-gray-400 max-w-2xl mx-auto leading-relaxed">
              At InVariant, we are fiercely committed to enhancing community health and fundamental well-being through high-quality, targeted pharmaceutical solutions.
            </p>
          </div>
        </div>

        {/* Carousel Block */}
        <div className="w-[100vw] relative left-[50%] right-[50%] -ml-[50vw] -mr-[50vw]">
          <Carousel
            className="w-full pl-4 md:pl-24"
            disableDrag={false}
          >
            <CarouselContent className="gap-6 pr-8">
              {items.map((item) => (
                <CarouselItem key={item.id} className="w-[85vw] sm:w-[50vw] md:w-[350px]">
                  <a href={item.url} className="group block relative w-full h-[400px] md:h-[450px]">
                    <Card className="overflow-hidden h-full w-full rounded-3xl bg-[#111111] border-white/10 shadow-2xl relative border">
                      {/* Image Frame */}
                      <div className="relative h-full w-full transition-all duration-[600ms] group-hover:h-1/2">
                        <img
                          src={item.image}
                          alt={item.title}
                          className="h-full w-full object-cover object-center pointer-events-none group-hover:scale-110 transition-transform duration-700"
                        />
                        {/* Fade overlay at bottom */}
                        <div className="absolute bottom-0 left-0 w-full h-32 bg-gradient-to-t from-black/80 to-transparent opacity-100 group-hover:opacity-0 transition-opacity duration-500 pointer-events-none" />
                        
                        {/* Default Floating Title (Visible when NOT hovered) */}
                        <div className="absolute bottom-6 left-6 right-6 transition-all duration-500 group-hover:opacity-0 group-hover:translate-y-4">
                           <h3 className="text-2xl font-bold tracking-tight text-white drop-shadow-xl">{item.title}</h3>
                        </div>
                      </div>

                      {/* Expanded Text Section (Slide up on hover) */}
                      <div className="absolute bottom-0 left-0 w-full px-8 transition-all duration-[600ms] h-1/2 flex flex-col justify-center bg-[#111111] border-t border-white/10 opacity-0 group-hover:opacity-100 translate-y-12 group-hover:translate-y-0">
                        <h3 className="text-2xl font-bold tracking-tight text-white mb-3">{item.title}</h3>
                        <p className="text-gray-400 text-sm md:text-base leading-relaxed">
                          {item.summary}
                        </p>
                        <Button
                          variant="outline"
                          size="icon"
                          className="absolute bottom-6 right-6 border border-white/20 bg-transparent text-white hover:bg-white hover:text-black hover:-rotate-45 transition-all duration-500 rounded-full h-12 w-12 flex items-center justify-center shadow-[0_0_15px_rgba(255,255,255,0.1)]"
                        >
                          <ArrowRight className="size-5" />
                        </Button>
                      </div>
                    </Card>
                  </a>
                </CarouselItem>
              ))}
            </CarouselContent>
          </Carousel>
        </div>
      </div>
    </section>
  );
}
